"""empty message

Revision ID: 4c7b19d3c9c8
Revises: 4207d52f4229
Create Date: 2021-11-12 13:41:00.088729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7b19d3c9c8'
down_revision = '4207d52f4229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idPlanet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPlanet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_planet')
    # ### end Alembic commands ###
